# conda env create --file environment.yml
# mamba env create --file environment.yml
name: final_project
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - nbdime
  - pip
  - plotly
  - pyjanitor
  - pyprojroot
  - seaborn
  
